# Name of the composite action
name: Bittree

inputs:
  github_token:
    description: 'GitHub credentials'
    required: true

  image: 
    description: 'Image to update with Bittree library'
    required: true

runs:
  using: "composite"
  steps:
    - run: git clone -b testing-workflow https://${{inputs.github_token}}:x-oauth-basic@github.com/Flash-X/Bittree.git
      shell: bash
    - run: cd Bittree && maple image build --base=${{inputs.image}} bittree
      shell: bash
    - run: cd Bittree && maple container publish --image=bittree
      shell: bash
    - run: maple tag bittree ${{inputs.image}}
      shell: bash 
